### ISSUE TITLE
support for external taxonomies

### ISSUE THREAD

**Issue by m1ci** [freme-project/e-Entity#46]
This issue summarizes the efforts towards support for domain specific scenarios in e-Entity. Bellow is the initial email conversion provided by @koidl on Sep 4th 2015:

Wripl connect is a tool for financial analysts to identify key trends and developments in large open web content spaces. 

The tool offers topic related 'visual cards' (See attachment). Each card representing a topic has specific terms related to it. Example:

Investment Funds
-> Closed-End Funds
-> Exchange Trade Funds
-> Hedge Funds
-> Mutual Funds 
[...]

Problem: A miss match between the vocabulary used by the domain expert (in this case financial analyst) and the vocabulary used in FREME NER or e-Terminology.

The two main challenges 

1) Filtering (only allowing terms that match the domain experts vocabulary and the FREME (both NER and terminology) vocabulary. 

2) Matching (match FREME NER and e-Terminology vocabulary to the domain experts vocabulary (for example assign all entities that relate to 'Investment Fund' to investment fund.)

Solution: Currently the main idea...

1) Filtering should be simple but might result in a very small result set limiting the interesting (edge case) content findings. 

2) WRIPL provides a list of terms (that are based on feedback with the domain expert) and for each term a wikipedia page link. 

This list is provided to NER and e-Terminology which then use the wikipedia pages to train the matching mechanism. 

Timeline and road map: To be discussed! We need to develop this road map by mid September to ensure all resources (including wripl) can be moved into the same direction. 

Keeping in mind this is a real scenario. We have a financial domain expert within wripl and we are actively reaching out to the industry. 

Also once this works for the financial domain we can test the application of the same approach to other domains (e.g. Healthcare which IBM Watson is apparently focusing on).

Also part of this is multilinguality but lets get English working first.

**Comment by jnehring** [comment]
This issue is outdated. We already have a feature for domain specifiy ner now.
