### ISSUE TITLE
Feedback on topic detection

### ISSUE THREAD

**Issue by jnehring** [freme-project/e-Entity#50]
@m1ci  wrote

@koidl the topics and associated weights and labels are already provided as part of the output. See
http://api-dev.freme-project.eu/current/e-entity/freme-ner/documents/?informat=text&input=Berlin+is+in+Germany.&outformat=turtle&language=en&dataset=dbpedia&enrichement=dbpedia-categories

The categories information are not included by default. You need to add the enrichement=dbpedia-categories parameter to include also the topics as part of the output.

Any feedback is more than welcome.

**Comment by m1ci** [comment]
... waiting for feedback from @koidl and/or @xFran

**Comment by fsasaki** [comment]
@koidl and/or @xFran, if you have feedback on this could you please provide it in this issue? Thanks.

**Comment by xFran** [comment]
I'm busy right now. I have to write an app for Trinity College Dublin/FALCON Project. Soon as I have some time to implement topic detection in Wripl's application or Kevin has time to test it we will provide feedback. 
Sorry about this guys.

**Comment by xFran** [comment]
Ok. My other project is going well so, I may be able to take a look at this Monday.
Is there anything where I have to focus more my attention? Or just use some random text and check if the topics makes sense. Topic detection is working only for English? Maybe the last question it's a silly one. But hey! Is mine! :-)  

Any suggestions please?
Thanks in advance.

**Comment by jnehring** [comment]
I would suggest that you take text that is actually used by WRIPL and comes from one of the WRIPL domains, e.g. finance. It should be text where you have clear expectations what the topics are. I suggest you start with English text. I think it should work for all languages that FREME NER supports. So you can test other languages also as long as you understand them so you can judge if the topic detection is right.

**Comment by xFran** [comment]
Ok @jnehring. I will try to do may best following your recommendations.
Regarding languages I can test in English, Spanish and Romanian but is not supported by NER engine I believe (it will be nice to have it in the future) and Kevin in German. Those are the languages we manage here.

Thank you.

**Comment by m1ci** [comment]
Currently, entities can be enriched with categories only for entities spotted in English texts.
Note that the categories are retrieved from DBpedia. You can check all available categories for an entity by 1) visiting the DBpedia page for the entity and looking at dcterms:subject, or 2) query them via our Freme LDF endpoint at rv2622.1blu.de:5000/dbpedia-types

**Comment by xFran** [comment]
Thank you for the note @m1ci.

**Comment by xFran** [comment]
Hi all

I'm running some tests here. Please see the attached text file.

[test.txt](https://github.com/freme-project/e-Entity/files/15911/test.txt)

First cUrl command on FREME's production server
```
curl -v -d @test.txt "http://api.freme-project.eu/current/e-entity/freme-ner/documents/?informat=text&input=&outformat=json-ld&language=en&dataset=dbpedia"
```

Response:
```
{
  "timestamp": 1445250576139,
  "error": "Bad Gateway",
  "status": 502,
  "exception": "eu.freme.broker.exception.ExternalServiceFailedException",
  "path": "//e-entity/freme-ner/documents/"
* Closing connection 0
}
```
Second cUrl command on FREME's dev server
```
curl -v -d @test.txt "http://api-dev.freme-project.eu/current/e-entity/freme-ner/documents/?informat=text&input=&outformat=json-ld&language=en&dataset=dbpedia" 
```
Response:
```
HTTP/1.1 200 OK
```
But the strange part here is that even the response is 200 OK I don't have any entity spotted.

I really hope I did something wrong because if not this can affect Wripl a lot.

**Comment by jnehring** [comment]
@xFran 

You discovered a bug in FREME NER and i created a bug report for this: https://github.com/freme-project/freme-ner/issues/47

But the problem lies within the `&input=&outformat=...` part of your request. The input parameter overwrites the post body. So you submit an empty string to enrichment. I could reproduce the bug and when i remove the bit `&input=` then it works.

**Comment by xFran** [comment]
Second test

I'm using the same boxing articles as @jnehring used before.

FREME's production server 
I get the same error. No changes here.

In FREME's development server 
```
curl -v -d @test.txt "http://api-dev.freme-project.eu/current/e-entity/freme-ner/documents/?informat=text&input=&outformat=json-ld&language=en&dataset=dbpedia&enrichement=dbpedia-categories"
```

I get 3 entities and 11 categories not all related to boxing or sports but seems to make sense.

**Comment by jnehring** [comment]
The category system is not deployed on production. Please use dev for testing.

**Comment by xFran** [comment]
For the categories I used dev. I just wanted to see if any differences sporting entities between dev and prod.

**Comment by m1ci** [comment]
@xFran 
Your cURL is not OK. cURL by default sets the `Content-Type` header to `application/x-www-form-urlencoded` which is then incorrectly interpreted by the API. When calling the service set also the `Content-Type` header to an empty value using `-H "Content-Type:"`

    curl -v -d @test-2.txt "http://api-dev.freme-project.eu/current/e-entity/freme-ner/documents/?informat=text&input=&outformat=json-ld&language=en&dataset=dbpedia&enrichement=dbpedia-categories" -H "Content-Type:"

**Comment by xFran** [comment]
@m1ci 
Still no entities.

```
}(13:36:00) ○ [fran@xps] ~/Downloads 
→ curl -v -d @test.txt "http://api-dev.freme-project.eu/current/e-entity/freme-ner/documents/?informat=text&outformat=json-ld&language=en&dataset=dbpedia&enrichement=dbpedia-categories" -H "Content-Type:"

```

cUrl fixed.

**Comment by xFran** [comment]
Removing the first paragraph I get:

One entity

```
 {
    "@id" : "http://freme-project.eu/#char=10,17",
    "@type" : [ "nif:Phrase", "nif:Word", "nif:RFC5147String", "nif:String" ],
    "nif:anchorOf" : "Germany",
    "beginIndex" : "10",
    "endIndex" : "17",
    "referenceContext" : "http://freme-project.eu/#char=0,2889",
    "taClassRef" : "http://nerd.eurecom.fr/ontology#Location",
    "itsrdf:taConfidence" : 0.5323128034518319,
    "taIdentRef" : "dbpedia:Germany"
  }

and 11 categories.

The categories are not really relevant for this article.

Germany/German  is mentioned 13 times in the article so this entity is OK. China/China’s is mentioned 4 times and was not spotted as a entity.

**Comment by m1ci** [comment]
> @m1ci Still no entities.

I believe this is related to the https://github.com/freme-project/freme-ner/issues/41 issue

**Comment by jnehring** [comment]
Can you please move the discussion about getting no entities to a new GitHub issue? We should not mix up different topics in the same discussion.

**Comment by xFran** [comment]
I can move it into another GitHub issue no probs.
This is about "Feedback on topic detection" I don't know if this is a bug and/or if is there any relations between the issues or just my fault because I mess up  things. We have nothing clear yet and I don't know the code and the workflow of your application either.
If you don't mind, can you or @m1ci open the GitHub issue please if needed? 
You guys know better than me what is going on.

**Comment by fsasaki** [comment]
Hi @xFran , I think this issue is about whether this type of output
1   dbc:British_Islands 15.94680660984782
2   dbc:Slavic_countries_and_territories    15.821275727763961
(see top of the issue) is relevant for you, and if not what could be changed. Above type of output is not the entity identification itself but about the topic, I assume this is why @jnehring proposed to have here only topic detection related discussion and in a different issue discussion about entity detection itself.

**Comment by jnehring** [comment]
Actually I think this issue is too long. We should close it. I created #53 to collect information about the quality of topic detection. @xFran please start new issues for the bugs you discovered. The issue looks very similar to https://github.com/freme-project/freme-ner/issues/46 maybe you can link in your new issue to https://github.com/freme-project/freme-ner/issues/46
