### ISSUE TITLE
DBPedia Spotlight down?

### ISSUE THREAD

**Issue by jnehring** [freme-project/e-Entity#52]
Since beginning of the week I have problems with DBPedia Spotlight endpoint.

http://api-dev.freme-project.eu/current/e-entity/dbpedia-spotlight/documents?confidence=0.3&input=This+is+Germany&informat=text&language=en produces

```
{
  "exception": "eu.freme.broker.exception.BadRequestException",
  "path": "/e-entity/dbpedia-spotlight/documents",
  "message": "Parameter outformat has invalid value \"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8\"",
  "error": "Bad Request",
  "status": 400,
  "timestamp": 1443687941390
}
```

http://spotlight.sztaki.hu:2222/rest/annotate?text=First+documented+in+the+13th+century%2C+Berlin+was+the+capital+of+the+Kingdom+of+Prussia+%281701%E2%80%931918%29%2C+the+German+Empire+%281871%E2%80%931918%29%2C+the+Weimar+Republic+%281919%E2%80%9333%29+and+the+Third+Reich+%281933%E2%80%9345%29.+Berlin+in+the+1920s+was+the+third+largest+municipality+in+the+world.+After+World+War+II%2C+the+city+became+divided+into+East+Berlin+--+the+capital+of+East+Germany+--+and+West+Berlin%2C+a+West+German+exclave+surrounded+by+the+Berlin+Wall+from+1961%E2%80%9389.+Following+German+reunification+in+1990%2C+the+city+regained+its+status+as+the+capital+of+Germany%2C+hosting+147+foreign+embassies.&confidence=0.5&support=0&spotter=Default&disambiguator=Default&policy=whitelist&types=&sparql=

Which seems to be the DBPedia REST API is not accessible also.

**Comment by m1ci** [comment]
It seems its the DBpedia spotlight instance is down. It can be checked also via its GUI http://dbpedia-spotlight.github.io/demo/
Unfortunately, we don't maintain DBpedia spotlight so we cant do anything with this. I'll ping the maintainers if they can re-deploy it. This has been already reported https://github.com/dbpedia-spotlight/dbpedia-spotlight/issues/376

**Comment by jnehring** [comment]
It up again
