### ISSUE TITLE
Make DBPedia Spotlight endpoint configurable

### ISSUE THREAD

**Issue by jnehring** [freme-project/e-Entity#54]
Please find the part in e-Entity repo that configures the endpoint of DBPedia Spotlight. Then make it configurable via Spring externalized configuration:

http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html

The default value should be the original DBPedia Spotlight endpoint. 

More documentation: http://www.mkyong.com/spring3/spring-value-default-value/

Please implement it in a branch and do not merge it in the master branch before november 12th.

**Comment by josauder** [comment]
Implemented in branch integration-tests. See https://github.com/freme-project/Broker/issues/124
