### ISSUE TITLE
Is FREME NER case sensitive?

### ISSUE THREAD

**Issue by jnehring** [freme-project/e-Entity#64]
From D4.2:

the service is currently case sensitive: e.g. “fabrizio celli” using the ORCID dataset returns no result while Fabrizio Celi returns meaningful results

When this is true I believe this could easily be a low hanging fruit to improve FREME NER.

**Comment by m1ci** [comment]
Yes, FREME NER is trained on data with key sensitivity turned on
@nilesh-c please confirm.
We might train to train one more model with case-sensitivity turned off.

**Comment by jnehring** [comment]
any update here?

**Comment by m1ci** [comment]
nothing to report here. But, its on our todo list.

**Comment by m1ci** [comment]
@jnehring should we create new issue for this since this "question" kind of issue?

**Comment by jnehring** [comment]
I put it on the [Future feature list](https://docs.google.com/document/d/1F3KR4tsVgGkpcQSW1r0QAZQfw4LtmFv58XpZUs29rQs/edit). So there is no need for a new issue. I think for FREME 0.6 we already have so many features that we do not need to put this also on the plate.
