### ISSUE TITLE
NER to include endpoint of resource

### ISSUE THREAD

**Issue by pheyvaer** [freme-project/e-Entity#65]
When you perform NER on a text, you get the resources of the entities. However, when more information is needed about a resource, by using e-Link, the endpoint is needed, because we need the endpoint to create a template.

Is it possible to add the endpoint for each resource to the NIF?
This is especially important when the NIF is being used by multiple services, as a certain service might not know on which dataset e-entity was performed earlier on in the process.

**Comment by m1ci** [comment]
> Is it possible to add the endpoint for each resource to the NIF?

By adding this info to each entity will increase the NIF size significantly.

What if we better documented the templates. So that we include information such as: "this template can be used if you performed NER using the DBpedia dataset?". Will this help?

**Comment by pheyvaer** [comment]
But then you still have to know which dataset was used for e-entity, and this is not always the case.

**Comment by m1ci** [comment]
well, maybe you can derive the dataset by looking at the entity URIs?
http://dbpedia.org/resource/ for DBpedia
http://orcid.org/ for ORCID
...

**Comment by pheyvaer** [comment]
This is not possible, as the entity URI do not have to be related to the endpoint URI.

**Comment by m1ci** [comment]
true, but also entity URI does not need to be present in any endpoint.

Also note that for entity linking is used data which not necessarily should be deployed in some endpoint. So there are two assumptions here:
1) the client should be aware about the entity links from which domain they come
2) the clint should be aware in which datasets these entities are described

**Comment by m1ci** [comment]
IMO this is big and open research question: know in which endpoint a resource can be found. Closing the issue.
