### ISSUE TITLE
Exclamation marks problem?

### ISSUE THREAD

**Issue by nilesh-c** [freme-project/e-Entity#70]
Turin is spotted here:
```curl -d 'Welcome to Turin! It is the most important city in Italy, next to Rome and Florence.' -X POST "http://rv2622.1blu.de:8080/api/entities?language=en&dataset=dbpedia&numLinks=1"```

but not here:
```curl "http://api.freme-project.eu/0.4/e-entity/freme-ner/documents?input=Welcome%20to%20Turin20It%20is%20the%20most%20important%20city%20in%20Italy%2C%20next%20to%20Rome%20and%20Florence.&informat=text&outformat=turtle&language=en&dataset=dbpedia"```

In the second example Turin gets turned to Turin20It, looks like some str/replace post-processing was over the exclamation mark? @m1ci did you do something in e-Entity in order to fix https://github.com/freme-project/freme-ner/issues/37 maybe?

**Comment by m1ci** [comment]
you have typo in the second command. you have ...to%20Turin20It... but it should be to%20Turin/20It... note the missing %

... there is no str/replace post-processing

**Comment by nilesh-c** [comment]
Oops, sorry, URL encoding problems. Correct version for reference:

curl -X POST --header "Content-Type: text/plain" --header "Accept: text/n3" -d "Welcome to Turin! It is the most important city in Italy, next to Rome and Florence." "http://api.freme-project.eu/0.4/e-entity/freme-ner/documents?informat=text&outformat=turtle&language=en&dataset=dbpedia&mode=all"
