### ISSUE TITLE
Entity not related to the context

### ISSUE THREAD

**Issue by xFran** [freme-project/e-Entity#72]
cUrl command:
`curl -X POST --header "Content-Type: text/n3" --header "Accept: text/n3" "http://api.freme-project.eu/0.5/e-entity/freme-ner/documents?input=Nice%20to%20be%20here%20in%20Berlin.%20Berlin%20is%20the%20capital%20of%20the%20Germany.&informat=text&outformat=json-ld&language=en&dataset=dbpedia&mode=all"`

"Nice" is spotted as an entity and a location. I know it's a city in France but this is not the case in this context. "Nice to be here in Berlin. Berlin is the capital of the Germany."

This cannot be avoided. Am I right?

**Comment by m1ci** [comment]
you are right

**Comment by xFran** [comment]
Ok. Thanks @m1ci
